# Make

- name: Make sure the nginx directory exists
  file:
    path: "{{nginx_dir}}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory

- name: Make sure the nginx log directory exists
  file:
    path: "{{nginx_log_dir}}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory

- name: Make sure the sites-available, sites-enabled and conf.d directories exist
  file:
    path: "{{nginx_dir}}/{{item}}"
    owner: root
    group: root
    mode: 0755
    recurse: yes
    state: directory
  with_items: ["sites-available", "sites-enabled", "conf.d"]

# Install nginx
- include: install.yml

- name: Make sure mime.types file is up to date
  copy: src=mime.types dest="{{nginx_dir}}/mime.types" owner=root group=root mode=0644

- name: Make sure the nginx configuration is up to date
  template: src=nginx.conf.j2 dest="{{nginx_dir}}/nginx.conf"
