# from Ansibles.nginx

- name: Make sure the nginx group is present
  group:
    gid: "{{nginx_gid}}"
    name: "{{nginx_group}}"
    state: present

- name: Make sure the www directory is present
  file:
    path: "{{nginx_www_dir}}"
    state: directory

- name: Make sure the nginx user is present
  user:
    name: "{{nginx_user}}"
    uid: "{{nginx_uid}}"
    group: "{{nginx_group}}"
    comment: "Nginx user"
    home: "{{nginx_www_dir}}"
    shell: /bin/false
    state: present
    system: yes

- name: Set the right directory permissions for the www directory
  file:
    path: "{{nginx_www_dir}}"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0755
    state: directory
