
- include: install.yml

- name: Update rkhunter configuration
  template: src=etc_rkhunter.conf.j2 dest=/etc/rkhunter.conf owner=root group=root mode=0644


# NOTE: This should only be run when config files are known to be good
- name: Set baseline file properties
  command: rkhunter --propupd
  sudo: yes
  when: rkhunter_propupd

- name: Run checks
  command: rkhunter -c --skip-keypress
  sudo: yes
  when: rkhunter_run_checks|bool
  ignore_errors: yes

# TODO: Perform configuration check: sudo rkhunter -C
# Right, now getting error output: "Unknown configuration file option: "
# But rkhunter seems to be running correctly


- include: cron.yml
