- name: Update the hostname
  copy:
    content: "{{hostname_name}}"
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
  when: hostname_name != ""

- name: Run hostname cmd
  hostname:
    name: "{{hostname_name}}"
  when: hostname_name != ""
