- name: Ensure docker rabbitmq directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_rabbitmq_data_dir }}"
  tags:
    - install
    - upgrade


- name: Restart docker rabbitmq container
  sudo: yes
  shell: "docker restart {{ docker_rabbitmq_name }}"
  tags:
    - restart


- name: Run docker rabbitmq container
  docker:
    env: "{{ docker_rabbitmq_env }}"
    hostname: "{{ docker_rabbitmq_hostname }}"
    image: "{{ docker_rabbitmq_image }}"
    name: "{{ docker_rabbitmq_name }}"
    net: "{{ docker_rabbitmq_net }}"
    ports: "{{ docker_rabbitmq_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_rabbitmq_volumes }}"
  tags:
    - install
    - upgrade
