- name: Restart docker unoconv container
  sudo: yes
  shell: "docker restart {{ docker_unoconv_name }}"
  tags:
    - restart


- name: Run docker unoconv container
  docker:
    command: "{{ docker_unoconv_command }}"
    env: "{{ docker_unoconv_env }}"
    expose: "{{ docker_unoconv_expose }}"
    hostname: "{{ hostname_name }}"
    image: "{{ docker_unoconv_image }}"
    name: "{{ docker_unoconv_name }}"
    net: "{{ docker_unoconv_net }}"
    ports: "{{ docker_unoconv_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    volumes: "{{ docker_unoconv_volumes }}"
    volumes_from: "{{ docker_unoconv_volumes_from }}"
  tags:
    - install
    - upgrade
