- name: Ensure docker rsyslog logrotate config
  template:
    src: "{{ docker_rsyslog_log_rotate_source_file }}"
    dest: "/etc/logrotate.d/{{ docker_rsyslog_log_rotate_file }}"
    owner: root
    group: root
    mode: 0644
  tags:
    - install
    - settings


- name: Restart docker rsyslog container
  sudo: yes
  shell: "docker restart {{ docker_rsyslog_name }}"
  tags:
    - restart


- name: Ensure docker rsyslog directories exist
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_rsyslog_conf_dir }}"
    - "{{ docker_rsyslog_log_dir }}"
  tags:
    - install
    - upgrade


- name: Run docker rsyslog container
  docker:
    name: "{{ docker_rsyslog_name }}"
    state: running
    image: "centerforopenscience/rsyslog:latest"
    restart_policy: always
    hostname: "{{ hostname_name }}"
    env: "{{ docker_rsyslog_env }}"
    volumes:
      - "{{ docker_rsyslog_conf_dir }}/:/etc/rsyslog.d/"
      - "{{ docker_rsyslog_log_log_dir }}:/log"
  tags:
    - install
    - upgrade
