DEBUG: false

# SERVER SETTINGS
FORK: false  # Maybe true, false or intger
PORT: 1212
HOST: 0.0.0.0

MONGO_URI: mongodb://mongo:27017/
MONGO_DATABASE_NAME: jam

ELASTICSEARCH_URI: http://elasticsearch:9200/

NAMESPACE_BACKENDS:
  state: mongo
  logger: mongo
  storage: mongo

NAMESPACEMANAGER_BACKENDS:
  state: mongo
  logger: mongo
  storage: mongo

NAMESPACE_DEFAULT_BACKENDS:
  state: mongo
  logger: mongo
  storage: mongo

JWT_SECRET: Something!Super@Secret
