- name: Ensure docker waterbutler server directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_waterbutler_server_conf_dir }}"
    - "{{ docker_waterbutler_server_ssl_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker waterbutler server ssl configuration settings
  copy:
    src: "{{ docker_waterbutler_server_source_ssl_dir }}"
    dest: "{{ docker_waterbutler_server_ssl_dir }}"
    mode: 0640
  tags:
    - install
    - settings
    - upgrade


- name: Restart docker waterbutler server container
  sudo: yes
  shell: "docker restart {{ docker_waterbutler_server_name }}_{{ item }}"
  with_sequence: count={{ docker_waterbutler_server_instances }}
  when: docker_waterbutler_server_instances > 0
  tags:
    - restart


- name: Run docker waterbutler server container
  docker:
    command: "{{ docker_waterbutler_server_command }}"
    env: "{{ docker_waterbutler_server_env }}"
    expose: "{{ docker_waterbutler_server_expose }}"
    hostname: "{{ docker_waterbutler_server_hostname }}"
    image: "{{ docker_waterbutler_server_image }}"
    links: "{{ docker_waterbutler_server_links }}"
    name: "{{ docker_waterbutler_server_name }}_{{ item }}"
    net: "{{ docker_waterbutler_server_net }}"
    ports: "{{ docker_waterbutler_server_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
    tty: yes
    volumes: "{{ docker_waterbutler_server_volumes }}"
    volumes_from: "{{ docker_waterbutler_server_volumes_from }}"
  with_sequence: count={{ docker_waterbutler_server_instances }}
  when: docker_waterbutler_server_instances > 0
  tags:
    - install
    - upgrade
