- name: Restart docker memcached container
  sudo: yes
  shell: "docker restart {{ docker_memcached_name }}"
  tags:
    - restart


- name: Run docker memcached container
  docker:
    command: "{{ docker_memcached_command }}"
    expose: "{{ docker_memcached_expose }}"
    hostname: "{{ hostname_name }}"
    image: "{{ docker_memcached_image }}"
    name: "{{ docker_memcached_name }}"
    ports: "{{ docker_memcached_ports }}"
    pull: always
    restart_policy: always
    state: reloaded
  tags:
    - install
    - upgrade
