- name: Ensure docker tokumx directories exist
  sudo: yes
  file:
    state: directory
    path: "{{ item }}"
  with_items:
    - "{{ docker_tokumx_conf_dir }}"
    - "{{ docker_tokumx_data_dir }}"
  tags:
    - install
    - upgrade


- name: Copy docker tokumx configuration settings
  copy:
    src: "{{ docker_tokumx_source_conf_file }}"
    dest: "{{ docker_tokumx_conf_file }}"
    mode: 0644
  tags:
    - install
    - settings
    - upgrade


- name: Restart docker tokumx container
  sudo: yes
  shell: "docker restart {{ docker_tokumx_name }}"
  tags:
    - restart


- name: Run docker tokumx container
  docker:
    command: "{{ docker_tokumx_command }}"
    env: "{{ docker_tokumx_env }}"
    expose: "{{ docker_tokumx_expose }}"
    name: "{{ docker_tokumx_name }}"
    hostname: "{{ docker_tokumx_hostname }}"
    net: "{{ docker_tokumx_net }}"
    ports: "{{ docker_tokumx_ports }}"
    pull: always
    restart_policy: always
    image: "{{ docker_tokumx_image }}"
    state: reloaded
    volumes: "{{ docker_tokumx_volumes }}"
  tags:
    - install
    - upgrade
