waterbutler_env: staging
waterbutler_config_dir: "/opt/waterbutler"
waterbutler_log_dir: "/var/log/waterbutler"

waterbutler_redis_dir: "/opt/redis"
waterbutler_rabbitmq_dir: "/opt/rabbitmq"

waterbutler_osfstorage_pending_dir: "/opt/osfstorage/pending"
waterbutler_osfstorage_complete_dir: "/opt/osfstorage/complete"

waterbutler_instances: 2
waterbutler_start_port: 7770
