- name: Ensure docker log rotate config
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/docker
    owner: root
    group: root
    mode: 0644
  tags:
    - v1.5
    - v1.7
    - v1.8
    - settings


- name: Update APT package cache
  apt: update_cache=yes
  sudo: yes
  tags:
    - v1.5
    - v1.7
    - v1.8


- name: Uninstall previous docker
  shell: dpkg --remove docker-engine; apt-get purge -y lxc-docker*; apt-get purge -y docker.io*
  ignore_errors: yes
  tags:
    - v1.5
    - v1.7
    - v1.8


- name: Verify docker is not installed
  file:
    path: /usr/bin/docker
    state: absent
  tags:
    - v1.5
    - v1.7
    - v1.8


- name: Install docker system dependencies
  apt:
    pkg: "{{ item }}"
    state: latest
  with_items:
    - python-pip
    - curl
    - ca-certificates
  tags:
    - v1.5
    - v1.7
    - v1.8


- name: Install docker system dependencies (v1.7, v1.8)
  shell: apt-get install -y apparmor linux-image-extra-virtual linux-image-extra-$(uname -r)
  tags:
    - v1.7
    - v1.8


- name: Download Docker Engine deb (v1.8)
  get_url:
    url: "http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.8.2-0~{{ ansible_distribution_release }}_amd64.deb"
    dest: /tmp/docker-engine.deb
    force: yes
    mode: 0440
  tags:
    - v1.8


- name: Download Docker Engine deb (v1.7)
  get_url:
    url: "http://apt.dockerproject.org/repo/pool/main/d/docker-engine/docker-engine_1.7.1-0~{{ ansible_distribution_release }}_amd64.deb"
    dest: /tmp/docker-engine.deb
    force: yes
    mode: 0440
  tags:
    - v1.7


- name: Install docker-engine deb (v1.7, v1.8)
  shell: dpkg -i /tmp/docker-engine.deb
  tags:
    - v1.7
    - v1.8


- name: Install docker apt keys (v1.5)
  sudo: yes
  apt_key:
    id: 36A1D7869245C8950F966E92D8576A8BA88D21E9
    keyserver: "hkp://keyserver.ubuntu.com:80"
    state: present
  tags:
    - v1.5


- name: Install docker apt repository (v1.5)
  sudo: yes
  apt_repository:
    repo: "deb https://get.docker.com/ubuntu docker main"
    state: present
  tags:
    - v1.5


- name: Force pip upgrade
  sudo: yes
  shell: easy_install -U pip
  tags:
    - v1.5
    - v1.7
    - v1.8


- name: Install docker pip dependencies (v1.8)
  sudo: yes
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - "docker-py==1.4.0"
    - "python-apt"
  tags:
    - v1.8


- name: Install docker pip dependencies (v1.7)
  sudo: yes
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - "docker-py==1.2.3"
    - "python-apt"
  tags:
    - v1.7


# Stuck on v1.5 when needing to mount a single file.
# issue: https://github.com/ansible/ansible-modules-core/issues/1158
# pull: https://github.com/ansible/ansible-modules-core/pull/1744
- name: Install docker pip dependencies (v1.5)
  sudo: yes
  pip:
    state: latest
    name: "{{ item }}"
  with_items:
    - "docker-py==1.1.0"
    - "python-apt"
  tags:
    - v1.5


- name: Install docker (v1.5)
  sudo: yes
  apt:
    state: latest
    pkg: "lxc-docker-1.5.0"
  tags:
    - v1.5


- name: Disable inter-container communication, require explicitly linked containers
  lineinfile:
    dest: /etc/default/docker
    regexp: ^(#|)DOCKER_OPTS
    line: DOCKER_OPTS="--icc=false"
  tags:
    - v1.5
    - v1.7
    - v1.8


- name: Restart docker daemon (reapply firewall rules)
  sudo: yes
  service:
    name: docker
    state: restarted
  tags:
    - v1.5
    - v1.7
    - v1.8
    - restart
